exit if the mkdir calls fail

diff --git a/kanopy/updateifnewer b/kanopy/updateifnewer
--- a/kanopy/updateifnewer
+++ b/kanopy/updateifnewer
@@ -35,14 +35,12 @@ if [[ "$noscrape" == "" ]] ; then
     screenscrape=-s
 fi
 
-mkdir -p $DATADIR/records
-mkdir -p $DATADIR/incoming_zip
-mkdir -p $DATADIR/incoming
-mkdir -p $DATADIR/processed_zip
-mkdir -p $DATADIR/incoming_sorted
-mkdir -p $DATADIR/processed
-mkdir -p $DATADIR/updates_incoming
-mkdir -p $DATADIR/screenshots
+mkdir -p $DATADIR/records $DATADIR/incoming_zip $DATADIR/incoming $DATADIR/processed_zip $DATADIR/incoming_sorted $DATADIR/processed $DATADIR/updates_incoming $DATADIR/screenshots
+if [[ $? != 0 ]]; then
+    Echo "mkdir command failed, nothing else is going to work"
+    exit 1
+fi
+
 #if [[ ! -d $COMMONDIR/node_modules ]] ; then
 #    Echo "Node modules not installed in common directory.  Exiting"
 #    exit 1
diff --git a/swank/updateifnewer b/swank/updateifnewer
--- a/swank/updateifnewer
+++ b/swank/updateifnewer
@@ -47,10 +47,12 @@ find_column_with_value() {
     echo "-1"
 }
 
-mkdir -p $DATADIR/incoming
-mkdir -p $DATADIR/screenshots
-mkdir -p $DATADIR/combined
-mkdir -p $DATADIR/tmp
+mkdir -p $DATADIR/incoming $DATADIR/screenshots $DATADIR/combined $DATADIR/tmp
+if [[ $? != 0 ]]; then
+    Echo "mkdir failed, nothing else is going to work"
+    exit 1
+fi
+
 #if [[ ! -d $COMMONDIR/node_modules ]] ; then
 #    Echo "Node modules not installed in common directory.  Exiting"
 #    exit 1
